### ISSUE TITLE
Error on using composer to install package

### ISSUE THREAD

**Issue by mdunbavan** [caouecs/Laravel-SirTrevorJS#13]
Hi,

Upon using Laravel 5 and this package I have come across this error when doing composer install command:

```
composer require caouecs/sirtrevorjs
Please provide a version constraint for the caouecs/sirtrevorjs requirement: 1.4.11
```

then I press return and I get this:

```
  Problem 1
    - Installation request for caouecs/sirtrevorjs 1.4.11 -> satisfiable by caouecs/sirtrevorjs[1.4.11].
    - caouecs/sirtrevorjs 1.4.11 requires thujohn/twitter ~1.2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Can you help at all...?

**Comment by caouecs** [comment]
I think it's same problem than #8

**Comment by mdunbavan** [comment]
hi @caouecs how do I add this in? Do I add thujohn twitter in after composer install of this package?

**Comment by caouecs** [comment]
No, this week-end, I will do two branchs, one for Laravel4 and one for Laravel5

**Comment by mdunbavan** [comment]
@caouecs thats great, I will wait to see it come through. Cheers

**Comment by caouecs** [comment]
Hello,
@mdunbavan I did a branch for Laravel 5, I don't test it yet. But you can test ;)

    "caouecs/sirtrevorjs": "2.0.x-dev"

**Comment by mdunbavan** [comment]
Hi @caouecs I still get the error:

```
roblem 1
    - Installation request for caouecs/sirtrevorjs 2.0.x-dev -> satisfiable by caouecs/sirtrevorjs[2.0.x-dev].
    - caouecs/sirtrevorjs 2.0.x-dev requires thujohn/twitter 2.0.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

**Comment by caouecs** [comment]
same problem, but it seems it's good version for Laravel5

**Comment by mdunbavan** [comment]
whats the best solution for this to work. It's now installed but I cannot publish config files to get correct paths for the CSS assets or js assets?

**Comment by caouecs** [comment]
This evening, I will change the way to publish config and assets

**Comment by mdunbavan** [comment]
cheers that would be awesome :)

**Comment by caouecs** [comment]
now you can publish config

**Comment by mdunbavan** [comment]
Cheers @caouecs please can you allow it to use the eventable.js and underscore? Its not adding it when I am using {!! SirTrevorJs::scripts() !!}. Its adding the source for sir trev but missing its dependancies

**Comment by caouecs** [comment]
Hello @mdunbavan ,
sorry for the delay.

So, you can define the list of scripts in the config file.
