### ISSUE TITLE
Issue on the JS files not outputting in the tags properly

### ISSUE THREAD

**Issue by mdunbavan** [caouecs/Laravel-SirTrevorJS#14]
Hey @caouecs

Nothing too major here.

Just been testing this and on the face of it the package seems to be playing nicely with laravel 5 in configuration but on the frontend nothing is happening for instance its not publishing the js files and then  rendering them on the front end with the usual tags added.

This results in backbone.js and eventable not working and giving errors. I also noticed the block types in the js in the footer were being rendered out like flat html so I wondered if this was because it needed to spit the selected block types out as {!! !!} laravel 5 items? Not sure might be worth looking at. I also noticed that editing the config file did nothing once saved.

I am not sure if you have played with it yet or if anyone else has but thats whats happening at the moment with me.

Cheers,
Mark

**Comment by caouecs** [comment]
Hello @mdunbavan,
I think all it's ok now
