### ISSUE TITLE
Compatibility with SirTrevor 0.5?

### ISSUE THREAD

**Issue by Zae** [caouecs/Laravel-SirTrevorJS#15]
It seems that the current version is not compatible with the newest (currently beta) version of SirTrevor. Only the first paragraph is rendered, after that stuff breaks.

It looks like they added some Html features to the serialized, this causes the Parsedown::lines() method to strip the rest.

~~~json
{"data":[{"type":"text","data":{"text":"<p>Tiramisu lemon drops sesame snaps. Sugar plum macaroon halvah cake candy canes pastry topping. Tart muffin liquorice tootsie roll pudding cheesecake tootsie roll jelly-o.</p><p>Lollipop jelly candy canes pie pastry jujubes wafer. Chocolate bar toffee sesame snaps jelly beans liquorice lollipop. Jelly-o jelly tiramisu carrot cake topping dessert bonbon candy canes marzipan. Bonbon wafer fruitcake fruitcake candy canes.</p><p>Pastry fruitcake pastry tootsie roll soufflé fruitcake tootsie roll gummi bears. Tiramisu pastry toffee chocolate bar candy biscuit topping. Croissant macaroon sweet.</p><p>Brownie croissant biscuit wafer gummi bears sugar plum. Chocolate bar gingerbread ice cream marzipan sesame snaps pastry tootsie roll gummi bears chocolate. Liquorice cake caramels danish chupa chups.</p><p>Candy cupcake danish chocolate cake pudding chocolate bar jelly-o cake. Cake jujubes gummies tootsie roll. Croissant lemon drops chocolate bar. Apple pie brownie halvah chocolate bar icing fruitcake tootsie roll oat cake.</p>","isHtml":true}}]}
~~~

**Comment by caouecs** [comment]
Hello,
effectively, it's not compatible with v0.5, because I don't use this version. But I think it's possible to update the converter of text with "isHtml" parameter.

**Comment by caouecs** [comment]
Hello,
you can test this pull request #16

**Comment by Zae** [comment]
Wow, you are very fast. I'll test it tomorrow when I'm back at the office.

Thanks!
Op 25 mrt. 2015 20:40 schreef "Fred Delrieu" <notifications@github.com>:

**Comment by caouecs** [comment]
it's ok ?

**Comment by Zae** [comment]
Sorry, I haven't been able to test it extensively but in a quick test everything seemed to work correctly.
