### ISSUE TITLE
Where can i get en.js in locales ?

### ISSUE THREAD

**Issue by odin88** [caouecs/Laravel-SirTrevorJS#17]
Do I need to download it manually or by installing this package the file is already included ?

![2015-04-12_4-26-08](https://cloud.githubusercontent.com/assets/680300/7103150/38e78ada-e0cc-11e4-91a6-9cced37c067c.png)

**Comment by xFlatlinex** [comment]
I'm having the same problem, it requires it in the code as a separete script, but it's not separate, it's included in the mail trevor.js file.

**Comment by caouecs** [comment]
Hello,
I will change the code to not include en.js by default, and add a configuration option to add language or not

**Comment by caouecs** [comment]
Hello,
I fixed the problem:

* master ( laravel 5 version ) : https://github.com/caouecs/Laravel-SirTrevorJS/commit/db3f50e8a9723172dcc372245ca8f1e46392eeba
* laravel 4 : https://github.com/caouecs/Laravel-SirTrevorJS/commit/98b7dc98863cb6d7cc888b0e57dedc7a9f2d0e76
