### ISSUE TITLE
Unexpected token & blocktypes

### ISSUE THREAD

**Issue by odin88** [caouecs/Laravel-SirTrevorJS#18]
This is the generated javascript

![2015-04-12_4-43-21](https://cloud.githubusercontent.com/assets/680300/7103189/805ef0cc-e0ce-11e4-8076-89c5c9a48894.png)

**Comment by caouecs** [comment]
Hello,
I don't have your problem. How do you include the script in Blade view ?

**Comment by odin88** [comment]
{!! SirTrevorJs::scripts() !!}

**Comment by odin88** [comment]
![2015-04-22_22-23-16](https://cloud.githubusercontent.com/assets/680300/7276703/30a5a008-e93e-11e4-80cb-59b2a5ee0eb7.png)

**Comment by ArranJacques** [comment]
I've got the same problem. I believe this is because the view files are using the double curly brace syntax `{{ $ouput }}`, which escapes special characters. Should be updated to use `{!! $output !!}`.

See http://laravel.com/docs/5.0/templates#other-blade-control-structures

**Comment by caouecs** [comment]
Hello,
you can test the develop branch.

**Comment by caouecs** [comment]
@odin88 it's good now ?
