### ISSUE TITLE
New blocktypes

### ISSUE THREAD

**Issue by xtrasmal** [caouecs/Laravel-SirTrevorJS#22]
Is there documentation on creating newblock types?
Can I see some examples on how you people integrated this in your backends?

**Comment by caouecs** [comment]
Hello,
no doc yet. But to add a block is easy.

* update SirTrevorJsConverter class with $blocks variable
* add your converter in Converter directory

**Comment by GregoryClaeyssens** [comment]
you can't add a block without editing your code...?

**Comment by GregoryClaeyssens** [comment]
I'll make a PR for easy custom block creation, maybe some documentation to

**Comment by caouecs** [comment]
Hello,
you can create your own converter, extend SirTrevorJsConverter, and use customBlocks variable.

**Comment by GregoryClaeyssens** [comment]
Hi Couacs;
Thank you for the quick reply. Let me elaborate: on the sirtrevorjs end adding a custom block went without any hastle. On the converter side I have created a Converter, extending the BaseConverter...
You lost me at customBlocks variable ;) no mention of this in docs, nor in code...

**Comment by GregoryClaeyssens** [comment]
I'v already made some (rather small) to SirTrevorJsConverter class so you can easily add custom converters through the config file. Let me know if this is already possible, otherwise i make it a PR

**Comment by caouecs** [comment]
Look SirTrevorJsConverter class and you will see the variable customblock

**Comment by GregoryClaeyssens** [comment]
Ok, found it, appears I was still on 2.2 instead of 2.3.
I created the class and extend SirTrevorJSConverter, added my converters (namespaced) in the customblock, but I since my SirTrevorJSConverter has another namespace it's never used. I using my SirTrevorJSConverter in app.php (aliases) but that changed nothing. Do I now need to extend SirTrevorJS class to? Since the render method will always use your Converter... Am i missing something obvious here?

**Comment by GregoryClaeyssens** [comment]
Never mind @caouecs , this works perfectly when using accessor to convert the json. I do have a question though. I can't understand why you did not add an optional array in the config file for custom blocks. This way there would be no need to extend SirTrevorJsConverter and you can happily use the aliases in blade templates etc... Also it would be kind of self-explanatory for new users when seeing a customblocks variable in config.

**Comment by caouecs** [comment]
Hello,
because I had a class which extended SirTrevorJsConverter, so I used this method.

If you prefer by file config, no problem. Do a pull request ;)

**Comment by sweet-greg** [comment]
Hi @caouecs I'm trying to make my PR but i'm not able to.
`You may not have permission to access Laravel-SirTrevorJS. `

Checked my SSH keys etc, I was wondering if you had an idea? Maybe you disabled this or something?
