### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by UdaraJay** [caouecs/Laravel-SirTrevorJS#27]
Is the master branch missing the assets? I can't seem to get this to work with laravel anymore... 
Would really appreciate it if I could get a copy that works with larval 5 for a project!

**Comment by caouecs** [comment]
Hello,
this project works on Laravel 5... we don't need assets of SirTrevorJs&Co in this project. This project is just PHP and Laravel, not JS.

**Comment by UdaraJay** [comment]
Got it to work on laravel 5.1!
I confused it with an older fork of the project that had the assets somehow, sorry!

Thanks very much! This is very useful!

**Comment by caouecs** [comment]
no problem ;)
